/*
 * SmartSalesAdvisor: A Decision Support Tool for Microentrepreneurs 
 * LETICIA DAVILA NICANOR
 * Laboratorio de Evaluación y Calidad de Software del 
 * Centro Uiversitario UAEM Valle de Mexico 
 * Universidad Autónoma del Estado de México
 */

//package SmartSalesAdvisor;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author LETICIA DAVILA NICANOR
 */
public class forms_SE extends javax.swing.JFrame {

    /**
     * Creates new form formularioSE
     */
    public forms_SE() {
        initComponents();
        setTitle("Decision-Making System for Sales Forecast Diagnosis");
        setResizable(true);
        this.setLocationRelativeTo(null);
        texto.setEditable(false);
    }

    /**
     * This method is automatically invoked during object construction to initialize
     * the instances of user interface components. 
     * NOTE: This code is auto-generated by the GUI Form Editor and should not be modified manually,
     * as it will be overwritten during regeneration.
    */

  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Freestyle Script", 0, 30)); // NOI18N
        jLabel2.setText("to the Sales Strategy ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_1.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Freestyle Script", 0, 30)); // NOI18N
        jLabel5.setText("Diagnosis System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(36, 36, 36))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 178));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.gray));

        jButton1.setText("Start Assessment");
        jButton1.setToolTipText("Click to start the assessment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jLabel6.setText("To begin the analysis, please");

        jLabel3.setText(" the Start Assessment button");

        jLabel7.setText("and respond according to the conditions");

        jLabel8.setText("of your microenterprise.");

        jButton2.setText("Exit");
        jButton2.setToolTipText("Click to exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        //SYSTEM IS INITIALIZING. LAUNCHING SYSTEM:EVENT_JBUTTON1ACTIONPERFORMED
        int a, b, c;

        a = JOptionPane.showConfirmDialog(rootPane, "At what production level do total revenues equal total costs?", null, YES_NO_OPTION); 
        
        //ASSESSMENT OF THE BREAK-EVEN POINT ACCORDING TO THE PRINCIPLES OF BUSINESS ECONOMICS.

        if (a == 0) {
            String dg = "_______________________________________\n"
                    + "- SmartSalesAdvisor:A Decision Support   \n"
                    + "-     Tool for Microentrepreneurs        \n"
                    + "_________________________________________\n"
                    + "-         DIAGNOSIS                      \n"
                    + "_________________________________________\n"
                    + "- There is a balance point between       \n"
                    + "- costs and revenues.                    \n"
                    + "_________________________________________\n";

            texto.setText(dg);
        } else if (a == 1) {
            b = JOptionPane.showConfirmDialog(rootPane, "Are total sales (total revenue) greater than total costs?", null, YES_NO_OPTION);
            if (b == 0) {

                String dg = "_________________________________________\n"
                        + "- SmartSalesAdvisor:A Decision Support   \n"
                        + "-     Tool for Microentrepreneurs        \n"
                        + "_________________________________________\n"
                        + "-         DIAGNOSIS                      \n"
                        + "_________________________________________\n"
                        + "- The company is in a PROFIT scenario!!  \n"
                        + "_________________________________________\n";

                texto.setText(dg);
            } else if (b == 1) {

              raw_material_costs();

            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }
    
   private void raw_material_costs(){
   //ANALYZE RAW MATERIAL COSTS

        int c;
        c = JOptionPane.showConfirmDialog(rootPane, "Do the raw material costs fluctuate in the short term (over a period of 3 months)?", null, YES_NO_OPTION);
        if (c == 0) {
            price_review();
           
        } else if (c == 1) {
            String dg = "________________________________________\n"
                        + "- SmartSalesAdvisor:A Decision Support\n"
                        + "-     Tool for Microentrepreneurs     \n"
                        + "______________________________________\n"
                        + "-         DIAGNOSIS                   \n"
                        + "______________________________________\n"
                        + "- A profit scenario is inferred.      \n"
                        + "- Although raw material costs         \n"
                        + "- do not fluctuate in the short term, \n"
                        + "- they may change over a longer period.\n"
                        + "_______________________________________\n";

            texto.setText(dg);
        }
    }
    private void price_review(){

       //PERFORM AN ANALYSIS OF INNOVATION OR MATERIAL SUBSTITUTION

        int c1, c2, c3;

        c1 = JOptionPane.showConfirmDialog(rootPane, "Have you carried out a price review?", null, YES_NO_OPTION);

        if ((c1 == 1)) {
            String dg = "________________________________________\n"
                        + "- SmartSalesAdvisor:A Decision Support\n"
                        + "-     Tool for Microentrepreneurs     \n"
                        + "______________________________________\n"
                        + "-         DIAGNOSIS:ALERT!!           \n"
                        + "______________________________________\n"
                        + "-  The company needs to conduct       \n"
                        + "-        a price review!!             \n"
                        + "______________________________________";

            texto.setText(dg);
        } else {
            c2 = JOptionPane.showConfirmDialog(rootPane, "Have you conducted a supplier evaluation?", null, YES_NO_OPTION);
            if ((c2 == 1)) {
                String dg = "________________________________________\n"
                          + "- SmartSalesAdvisor:A Decision Support\n"
                          + "-     Tool for Microentrepreneurs     \n"
                          + "______________________________________\n"
                          + "-         DIAGNOSIS:ALERT!!           \n"
                          + "______________________________________\n"
                          + "- The company needs to conduct        \n"
                          + "- a SUPPLIER EVALUATION!!             \n"
                          + "______________________________________";

                texto.setText(dg);
            } else {
                c3 = JOptionPane.showConfirmDialog(rootPane, "Have you made any innovations or replaced materials?", null, YES_NO_OPTION);
                if ((c3 == 1)) {
                    String dg = "________________________________________\n"
                              + "- SmartSalesAdvisor:A Decision Support  \n"
                              + "-     Tool for Microentrepreneurs       \n"
                              + "________________________________________\n"
                              + "-         DIAGNOSIS:ALERT!!             \n"
                              + "________________________________________\n"
                              + "- The company needs to implement        \n"
                              + "- innovation and material substitution. \n"
                              + "________________________________________\n";

                    texto.setText(dg);
                } else {
                    advertising();
                  
                }
            }

        }
    }

    private void advertising(){
  
        //Perform an analysis of advertising

        int d, d1, d2;
        d = JOptionPane.showConfirmDialog(rootPane, "Do advertising costs remain stable in the short term?", null, YES_NO_OPTION);
        if ((d == 1)) {
            String dg = "________________________________________\n"
                      + "- SmartSalesAdvisor:A Decision Support\n"
                      + "-     Tool for Microentrepreneurs     \n"
                      + "______________________________________\n"
                      + "-         DIAGNOSIS:                  \n"
                      + "______________________________________\n"
                    + "- Sales stability exists, but           \n"
                    + "- it is recommended to monitor          \n"
                    + "- and adjust advertising strategies     \n"
                    + "- to stay aligned with market changes   \n"
                    + "- and audience needs                    \n"
                    + "________________________________________\n";

            texto.setText(dg);
        } else {
            d1 = JOptionPane.showConfirmDialog(rootPane, "Is your advertising primarily conducted through social media?", null, YES_NO_OPTION);
            if ((d1 == 1)) {
                String dg = "________________________________________\n"
                          + "- SmartSalesAdvisor:A Decision Support\n"
                          + "-     Tool for Microentrepreneurs     \n"
                          + "______________________________________\n"
                          + "-         DIAGNOSIS:                  \n"
                          + "______________________________________\n"
                          + "- Using SOCIAL MEDIA for advertising  \n"
                          + "- is recommended                      \n"
                          + "______________________________________\n";

                texto.setText(dg);
            } else {
                d2 = JOptionPane.showConfirmDialog(rootPane, "Have you analyzed statistics such as views, plays, subscriptions, recommendations, and comments regarding your advertising on social media?", null, YES_NO_OPTION);
                if ((d2 == 1)) {
                String dg = "________________________________________\n"
                          + "- SmartSalesAdvisor:A Decision Support\n"
                          + "-     Tool for Microentrepreneurs     \n"
                          + "______________________________________\n"
                          + "-         DIAGNOSIS:                  \n"
                          + "______________________________________\n"
                        + "- It is recommended to analyze social media\n"
                        + "- usage and its relationship between  \n"
                        + "- advertising and sales levels.       \n" 
                        + "______________________________________\n";

                texto.setText(dg); 
                } else {
                    salaries();

                }
            }
        }
    }
    
    private void salaries() {

    //ANALYZE SALARIES

        int e; 
        e = JOptionPane.showConfirmDialog(rootPane, "Is there an employment contract in place for your staff?", null, YES_NO_OPTION);
        if ((e == 0)) {
               String dg = "________________________________________\n"
                          + "- SmartSalesAdvisor:A Decision Support\n"
                          + "-     Tool for Microentrepreneurs     \n"
                          + "______________________________________\n"
                          + "-         DIAGNOSIS: CONGRATULATIOS!! \n"
                          + "______________________________________\n"
                          + "-The company is not incurring losses!!\n"
                          + "_______________________________________\n";

                texto.setText(dg);     
        } else{
        String dg = "________________________________________\n"
                          + "- SmartSalesAdvisor:A Decision Support\n"
                          + "-     Tool for Microentrepreneurs     \n"
                          + "______________________________________\n"
                          + "-         DIAGNOSIS:                  \n"
                          + "______________________________________\n"
                          + "- The company is subject to the productivity \n"
                          + "- of the contracted worker (freelance),\n"
                          + "- increasing the risk of losses.       \n"
                          + "_______________________________________\n";

                texto.setText(dg);       
        }
    }
    


    // Variables declaration 
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration
}
